<div id="banner" class="container_banner container_home">
	<div class="box_banner">
		<img class="content_banner" src='<?php echo $this->getViewFileUrl('images/forest.jpg'); ?>'>
	</div>
	<div class="box_banner">
		<img class="content_banner" src='<?php echo $this->getViewFileUrl('images/jungle.jpg'); ?>'>
	</div>
	<div class="box_banner">
		<img class="content_banner" src='<?php echo $this->getViewFileUrl('images/trees.jpg'); ?>'>
	</div>
	<div class="box_banner">
		<img class="content_banner" src='<?php echo $this->getViewFileUrl('images/waterfall.jpg'); ?>'>
	</div>
	<div class="box_banner">
		<img class="content_banner" src='<?php echo $this->getViewFileUrl('images/waterandmountains.jpg'); ?>'>
	</div>
</div>

<script type="text/x-magento-init">
    {
       "*": {
           "banner": {}
       }
   }
</script>